title: "Jérôme Bétrisey"
author: "Jérôme Bétrisey"
# description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
description: "Personal website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
excerpt_separator: <!-- excerpt-end -->
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "JeromeBetrisey_CV.pdf", title: "CV"}
  - {title: "Publications", url: "https://ui.adsabs.harvard.edu/search/q=%20%20author%3A%22B%C3%A9trisey%2C%20J.%22&sort=date%20desc%2C%20bibcode%20desc&p_=0"}
#  - {file: "README.md", title: "About me"}
  - {file: "aboutme.md", title: "About me"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/JeromeBetrisey"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0002-6462-3683"}
  - {title: ADS, icon: book-open, url: "https://ui.adsabs.harvard.edu/search/q=%20%20author%3A%22B%C3%A9trisey%2C%20J.%22&sort=date%20desc%2C%20bibcode%20desc&p_=0"}
  - {title: University, icon: external-link-alt, url: "https://www.unige.ch/sciences/astro/evolution/en/members/jerome-betrisey"}
#  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
